# Generated by Django 5.2.1 on 2025-05-13 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_discussion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='firebase_user_id',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='Firebase UID'),
        ),
    ]
