# Generated by Django 5.2.1 on 2025-05-19 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_discussion', '0002_discussion_firebase_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='is_stopped',
            field=models.BooleanField(default=False, verbose_name='Остановлено досрочно'),
        ),
    ]
