# Generated by Django 5.2.1 on 2025-05-19 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_discussion', '0003_discussion_is_stopped'),
    ]

    operations = [
    ]
