# Generated by Django 5.2.1 on 2025-05-21 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_discussion', '0004_auto_20250519_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomCharacter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('character', models.TextField(verbose_name='Описание характера')),
                ('discusser_type', models.CharField(choices=[('ai', 'AI - Обычная нейросеть'), ('cognitive', 'Cognitive - Аналитическая нейросеть')], default='ai', max_length=20, verbose_name='Тип нейросети')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('firebase_user_id', models.CharField(blank=True, max_length=128, null=True, verbose_name='Firebase UID')),
            ],
            options={
                'verbose_name': 'Пользовательский характер',
                'verbose_name_plural': 'Пользовательские характеры',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='discussion',
            name='selected_participants',
            field=models.TextField(blank=True, help_text='JSON строка с ID участников из настроек и пользовательских', null=True, verbose_name='Выбранные участники'),
        ),
    ]
